services:
  web-staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fe-insight-staging
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
